# Generated by Django 3.1.5 on 2021-01-12 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interviewing', 'Interviewing'), ('not-selected', 'Not-Selected'), ('selected', 'Selected')], default='pending', max_length=100)),
                ('date_applied', models.DateField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='post_created')),
                ('post_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('starred', models.CharField(choices=[('important', 'Important'), ('not-important', 'Not-Important')], default='not-important', max_length=20)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_link', models.URLField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-post_created',),
            },
        ),
    ]
